insert into public.clients (name) values ('Farmacias Similares'), ('Cliente de prueba'), ('Tiempo interno') on conflict (name) do nothing;
insert into public.activities (name) values
('Atención a cliente (mails, llamadas, minutas, tiempo de transportación a oficina de cliente)'),
('Reuniones en oficinas de Cliente (juntas, presentaciones, consulta de bases de datos, etc)'), ('Planeación Estratégica'), ('Planeación táctica'),
('Elaboración de presupuestos (carga en Arien, reportes financieros)'), ('Contratación (gestión de órdenes y materiales: envío al medio, confirmación)'),
('Monitoreo y seguimiento de campañas (monitoreo, recolocación, cancelaciones)'), ('Conciliación (confirmación con medios, bases de IBOPE, otro)'),
('Cierre Financiero (armado de carpetas)'), ('Post Buy Análisis (Campaña y redes sociales)'), ('Reportes de competencia, Investigación, Data y Análisis'),
('Atención a Medios/Proveedores'), ('Negociación'), ('Diseño'), ('Community Manager (Armado de parrillas, posteos, copy, solicitud y seguimiento de materiales)'),
('Tiempo Empresarial (juntas internas, festejos, otros)'), ('Gestión de equipo (Revisión de documentos antes de salir a Cliente, coach y capacitación, alineación de equipo, Reclutamiento y contratación)'), ('Comida')
on conflict (name) do nothing;
insert into public.employees (full_name, position, status) values
('Anaya García Carolina Sofía', 'Gerente Digital', 'Activo'), ('García Herrera Maricela', 'Gerente de Trade', 'Activo'), ('García Domínguez Fanny', 'Dirección General', 'Activo'), ('Alvarado Miranda Ana Luz', 'Gestión de Medios Off', 'Baja'), ('Martínez Trujillo Martha Patricia', 'Director de Operaciones', 'Activo'), ('Celis Almaraz Adriana', 'Director de Cuenta', 'Baja'), ('Troncoso Fuentes Jessica Alejandra', 'Gerente Back Office RH', 'Activo'), ('Hernández García Alberto Emmanuel', 'Diseñador Sr', 'Activo'), ('Millán Latapí Juan Pablo', 'Gerente de Nuevos Negocios', 'Activo'), ('García Islas Diego', 'n/a', 'Baja'), ('Zuñiga Jiménez Dafne Zoé', 'Community Manager', 'Activo'), ('Mata Flores Martha Alicia', 'Supervisor de Medios', 'Baja'), ('Ponce Acuña Tanya', 'Community Manager', 'Activo'), ('Santiago Valentinez Agustín', 'Ejecutivo de Cuenta', 'Activo'), ('Pérez Gutiérrez Arturo', 'Planner', 'Activo'), ('Méndez Arreola Maria Minerva', 'Supervisor de Medios', 'Activo'), ('Ramírez García Verónica', 'Director de Cuenta', 'Baja'), ('Celis Almaraz Ruth', 'Gerente de Finanzas', 'Baja'), ('Lamadrid Roch Eugenio', 'Productor digital', 'Activo'), ('Morán Arvizu Jesús Manuel', 'Coordinadora de Medios', 'Activo'), ('Velasco Magaña Martha Graciela', 'Supervisor de Medios', 'Activo'), ('Rodríguez Mondragón Jorge Luis', 'Analista de Datos', 'Activo'), ('Hernández Chaires David Ernesto', 'Planner', 'Baja'), ('Rizo Serrano Félix David', 'Analista de Datos', 'Activo'), ('Cruz Ocampo Jazmín Araceli', 'Ejecutiva de Cuenta', 'Activo'), ('Ibarra Arenas Patricia', 'Controler', 'Activo'), ('Ortiz Colín Diana', 'Planner', 'Activo'), ('Padilla Silva Karla Daniela', 'Ejecutivo de Cuenta', 'Activo'), ('De León Clorio Irais', 'Coordinadora de Medios', 'Activo'), ('Medrano Águila Susana Sunem', 'Supervisor de Medios', 'Baja'), ('Domínguez García Rebeca', 'Director de Cuenta', 'Activo'), ('Galeana Ruiz Vania Marleth', 'Coordinadora de Medios', 'Activo'), ('Méndez López Alejandro David', 'Ejecutivo de Cuenta', 'Activo'), ('Altamirano Reyes Luz Fernanda', 'Ejecutivo de Cuenta', 'Activo'), ('Hernández Cagal Ely Cristel', 'Becario', 'Activo'), ('Negrete González Diego Armando', 'Supervisor de Medios', 'Activo'), ('González Chávez Edmundo', 'Planner', 'Activo'), ('De Viana Cruz Brenda Gabriela', 'Asistente de Medios', 'Activo'), ('Dulce Daniela Nieto Saldaña', 'Community Manager', 'Activo'), ('Alonso Gutérrez Katya', 'Asistente de Medios', 'Activo'), ('González Guarneros José Antonio', 'Chofer / Mensajero', 'Activo'), ('Guerrero Portillo Dana Sofía', 'Diseñador Jr', 'Activo') on conflict do nothing;
