-- El catálogo inicial mezclaba "Apellidos Nombre(s)" con "Nombre(s) Apellidos".
-- Dejamos todos los registros conocidos en un formato único y legible.
update public.employees set full_name = 'Carolina Sofía Anaya García' where lower(btrim(full_name)) = lower('Anaya García Carolina Sofía');
update public.employees set full_name = 'Maricela García Herrera' where lower(btrim(full_name)) = lower('García Herrera Maricela');
update public.employees set full_name = 'Fanny García Domínguez' where lower(btrim(full_name)) = lower('García Domínguez Fanny');
update public.employees set full_name = 'Ana Luz Alvarado Miranda' where lower(btrim(full_name)) = lower('Alvarado Miranda Ana Luz');
update public.employees set full_name = 'Martha Patricia Martínez Trujillo' where lower(btrim(full_name)) = lower('Martínez Trujillo Martha Patricia');
update public.employees set full_name = 'Adriana Celis Almaraz' where lower(btrim(full_name)) = lower('Celis Almaraz Adriana');
update public.employees set full_name = 'Jessica Alejandra Troncoso Fuentes' where lower(btrim(full_name)) = lower('Troncoso Fuentes Jessica Alejandra');
update public.employees set full_name = 'Alberto Emmanuel Hernández García' where lower(btrim(full_name)) = lower('Hernández García Alberto Emmanuel');
update public.employees set full_name = 'Juan Pablo Millán Latapí' where lower(btrim(full_name)) = lower('Millán Latapí Juan Pablo');
update public.employees set full_name = 'Diego García Islas' where lower(btrim(full_name)) = lower('García Islas Diego');
update public.employees set full_name = 'Dafne Zoé Zúñiga Jiménez' where lower(btrim(full_name)) = lower('Zuñiga Jiménez Dafne Zoé');
update public.employees set full_name = 'Martha Alicia Mata Flores' where lower(btrim(full_name)) = lower('Mata Flores Martha Alicia');
update public.employees set full_name = 'Tanya Ponce Acuña' where lower(btrim(full_name)) = lower('Ponce Acuña Tanya');
update public.employees set full_name = 'Agustín Santiago Valentinez' where lower(btrim(full_name)) = lower('Santiago Valentinez Agustín');
update public.employees set full_name = 'Arturo Pérez Gutiérrez' where lower(btrim(full_name)) = lower('Pérez Gutiérrez Arturo');
update public.employees set full_name = 'María Minerva Méndez Arreola' where lower(btrim(full_name)) = lower('Méndez Arreola Maria Minerva');
update public.employees set full_name = 'Verónica Ramírez García' where lower(btrim(full_name)) = lower('Ramírez García Verónica');
update public.employees set full_name = 'Ruth Celis Almaraz' where lower(btrim(full_name)) = lower('Celis Almaraz Ruth');
update public.employees set full_name = 'Eugenio Lamadrid Roch' where lower(btrim(full_name)) = lower('Lamadrid Roch Eugenio');
update public.employees set full_name = 'Jesús Manuel Morán Arvizu' where lower(btrim(full_name)) = lower('Morán Arvizu Jesús Manuel');
update public.employees set full_name = 'Martha Graciela Velasco Magaña' where lower(btrim(full_name)) = lower('Velasco Magaña Martha Graciela');
update public.employees set full_name = 'Jorge Luis Rodríguez Mondragón' where lower(btrim(full_name)) = lower('Rodríguez Mondragón Jorge Luis');
update public.employees set full_name = 'David Ernesto Hernández Chaires' where lower(btrim(full_name)) = lower('Hernández Chaires David Ernesto');
update public.employees set full_name = 'Félix David Rizo Serrano' where lower(btrim(full_name)) = lower('Rizo Serrano Félix David');
update public.employees set full_name = 'Jazmín Araceli Cruz Ocampo' where lower(btrim(full_name)) = lower('Cruz Ocampo Jazmín Araceli');
update public.employees set full_name = 'Patricia Ibarra Arenas' where lower(btrim(full_name)) = lower('Ibarra Arenas Patricia');
update public.employees set full_name = 'Diana Ortiz Colín' where lower(btrim(full_name)) = lower('Ortiz Colín Diana');
update public.employees set full_name = 'Karla Daniela Padilla Silva' where lower(btrim(full_name)) = lower('Padilla Silva Karla Daniela');
update public.employees set full_name = 'Irais De León Clorio' where lower(btrim(full_name)) = lower('De León Clorio Irais');
update public.employees set full_name = 'Susana Sunem Medrano Águila' where lower(btrim(full_name)) = lower('Medrano Águila Susana Sunem');
update public.employees set full_name = 'Rebeca Domínguez García' where lower(btrim(full_name)) = lower('Domínguez García Rebeca');
update public.employees set full_name = 'Vania Marleth Galeana Ruiz' where lower(btrim(full_name)) = lower('Galeana Ruiz Vania Marleth');
update public.employees set full_name = 'Alejandro David Méndez López' where lower(btrim(full_name)) = lower('Méndez López Alejandro David');
update public.employees set full_name = 'Luz Fernanda Altamirano Reyes' where lower(btrim(full_name)) = lower('Altamirano Reyes Luz Fernanda');
update public.employees set full_name = 'Ely Cristel Hernández Cagal' where lower(btrim(full_name)) = lower('Hernández Cagal Ely Cristel');
update public.employees set full_name = 'Diego Armando Negrete González' where lower(btrim(full_name)) = lower('Negrete González Diego Armando');
update public.employees set full_name = 'Edmundo González Chávez' where lower(btrim(full_name)) = lower('González Chávez Edmundo');
update public.employees set full_name = 'Brenda Gabriela De Viana Cruz' where lower(btrim(full_name)) = lower('De Viana Cruz Brenda Gabriela');
update public.employees set full_name = 'Katya Alonso Gutiérrez' where lower(btrim(full_name)) = lower('Alonso Gutérrez Katya');
update public.employees set full_name = 'José Antonio González Guarneros' where lower(btrim(full_name)) = lower('González Guarneros José Antonio');
update public.employees set full_name = 'Dana Sofía Guerrero Portillo' where lower(btrim(full_name)) = lower('Guerrero Portillo Dana Sofía');
